update

diff --git a/service/brook_centos b/service/brook_centos
--- a/service/brook_centos
+++ b/service/brook_centos
@@ -38,45 +38,53 @@ read_config(){
 	[[ -z ${user_all} ]] && echo -e "${Error} Brook 配置文件中用户配置为空 !" && exit 1
 	protocol=$(cat ${CONF}|sed -n "1p")
 }
-do_start(){
-	check_running
-	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..." && exit 0
-	else
-		read_config
-		cd ${FILE}
-		echo -e "${Info} $NAME 启动中..."
-		ulimit -n 51200
-		servers_all=""
-		for ((integer = 1; integer <= ${user_all_num}; integer++)); do
+do_start() {
+  check_running
+  if [[ $? -eq 0 ]]; then
+    echo -e "${Info} $NAME (PID ${PID}) 正在运行..." && exit 0
+  else
+    read_config
+    cd ${FILE}
+    echo -e "${Info} $NAME 启动中..."
+    ulimit -n 51200
+
+    # 逐行处理用户配置，每行启动一个实例
+    for ((integer = 1; integer <= ${user_all_num}; integer++)); do
           user_text=$(echo "${user_all}" | sed -n "${integer}p")
           port=$(echo "${user_text}" | awk '{print $1}')
           password=$(echo "${user_text}" | awk '{print $2}')
           custom_protocol=$(echo "${user_text}" | awk '{print $3}')
 
-          # 如果 custom_protocol 为空，则使用默认的 protocol
+          # 如果 custom_protocol 为空，则使用默认的 protoco
           current_protocol="${custom_protocol:-$protocol}"
 
+          # 为每个配置构建单独的命令
           if [ "$current_protocol" == "server" ]; then
-            # brook servers -l ":9999 password" -l ":8888 password"
-            servers_all="${servers_all}-l \":${port} ${password}\" "
+            # brook server -l ":9999 password"
+            cmd="./brook server -l :${port} -p ${password}"
           elif [ "$current_protocol" == "wsserver" ]; then
-            # brook servers -l ":9999 password" -l ":8888 password"
-            servers_all="${servers_all}-l \":${port} ${password}\" "
+            # brook wsserver -l ":9999 password"
+            cmd="./brook wsserver -l :${port} -p ${password}"
           else
             # brook wsserver -l :9999 -p password
-            servers_all="${servers_all}-l:${port} -p ${password}"
+            cmd="./brook wsserver -l :${port} -p ${password}"
           fi
+
+          # 启动单个实例
+          echo -e "${Info} 启动配置: Port=${port}, Protocol=${current_protocol}"
+          echo $cmd >>"${LOG}"
+          eval nohup ${cmd} >>"${LOG}" 2>&1 &
+          sleep 1s  # 等待一秒，让进程有时间启动
     done
-		eval nohup ./brook ${protocol} $(echo ${servers_all}) >> "${LOG}" 2>&1 &
-		sleep 2s
-		check_running
-		if [[ $? -eq 0 ]]; then
-			echo -e "${Info} $NAME 启动成功 !"
-		else
-			echo -e "${Error} $NAME 启动失败 !"
-		fi
-	fi
+
+    sleep 2s
+    check_running
+    if [[ $? -eq 0 ]]; then
+      echo -e "${Info} $NAME 启动成功 !"
+    else
+      echo -e "${Error} $NAME 启动失败 !"
+    fi
+  fi
 }
 do_stop(){
 	check_running
